config/routes.rb
Rails.application.routes.draw do
    resources :posts
    root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def create
        @post = Post.new(post_params)
        @post.save
        
        redirect_to @post
    end
    
    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        
        redirect_to @post
    end
    
    def destroy
       @post = Post.find(params[:id])
       @post.destroy
       
       redirect_to posts_path
    end
    
    private
        def post_params
            params.require(:post).permit(:title, :content, :tag)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary ni Koji</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<style>
    .area-sizing {
        resize: none;
        width: 100%;
        height: 300px;
    }
    
    .field-sizing {
    	width: 50%;
    }
</style>
<div class="container">
<%= form_for @post do |f| %>

	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title, class: "field-sizing" %>
	</p>
	<p>
		<%= f.label :content %> <br>
		<%= f.text_area :content, class: "area-sizing" %>
	</p>
	<p>
		<%= f.label :tag %> <br>
		<%= f.text_field :tag %>
	</p>
	<p>
		<br>
		<%= f.submit 'Save Entry', class: "btn btn-primary" %>
    </p>
<% end %>
</div>

app/views/posts/edit.html.erb
<%= link_to 'Back', posts_path %>

<%= render 'form' %>

app/views/posts/index.html.erb
    <div class="jumbotron">
        <div class="container">
            <h1>Diary ni Koji</h1>
            <%= button_to "New Entry", new_post_path, method: :get, class: "btn btn-info btn-lg" %>
        </div>
    </div>

    <div class="container">
        <% @posts.each do |p| %>
            <div>
                <h2 style="display:inline-block"><%= p.title %></h2>
                <span style="float:right">
                    <%= link_to 'Show', post_path(p) %> |
                    <%= link_to 'Edit', edit_post_path(p) %> |
                    <%= link_to 'Delete', post_path(p), method: :delete, data: {confirm: "Delete entry \"" + p.title + "\"?"} %>
                </span>
            </div>
            <p>
                <p style="white-space: pre-wrap"><%= p.content %></p> <br>
                <small>tag: <%= p.tag %></small> <br>
                <br>
            </p>
            <hr>
        <% end %>
    </div>
  

app/views/posts/new.html.erb
<%= link_to 'Back', posts_path %>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to 'Back', posts_path %>

<div class="container">
    <h1><%= @post.title %></h1>
    <p style="white-space: pre-wrap"><%= @post.content %></p>
    <small>tag: <%= @post.tag %></small> <br><br>
    
    <%= button_to 'Edit', edit_post_path, method: :get, class: "btn btn-primary" %>
</div>